### ISSUE TITLE
New version not working on phones with a previous installation

### ISSUE THREAD

**Issue by carymc** [davidebukali/geobucket#10]
I had installed a previous version of GeoBucket, and then decided to upgrade to the newest version.  However, even though the installation appeared to be successful and I was able to use the app, buckets are not being captured.  The status tells me in green that it is working, but after I stop the tracking, no buckets have been captured.

**Comment by davidebukali** [comment]
Hi Cary, this is normal if you are not moving because a point is saved only when a distance greater than 5 meters is covered. If you are moving and points are not being saved then the upgrade process may be incomplete. Please  first remove the current version on your phone then do a new installation from the android market.

**Comment by davidebukali** [comment]
This was fixed in the latest version on the android market
