### ISSUE TITLE
Buckets captured even when status is orange

### ISSUE THREAD

**Issue by carymc** [davidebukali/geobucket#11]
On a Samsung Galaxy Mini Pocket running Android 2.3.6, the status tells me in orange to "wait while the gps accuracy is being improved"; however, when I stop tracing, the number of buckets does get updated.  So it appears to be working even though the status isn't green, which is slightly confusing to the user.

**Comment by davidebukali** [comment]
When you are within a building, the accuracy sometimes changes rapidly between the allowed range of values and values that are above the set accuracy for which buckets should not be saved, this could lead to the buckets being updated even though the status is orange. It is not a problem however because these points(buckets) are accurate values which can be used on the map. It's up to the user to set the accuracy for the app otherwise a default value of 20 meters is used, also remember to save the accuracy setting after making changes;

If the problem persists, please unistall the current version you have and do a new installation from the android market.
